import { nanoid } from 'nanoid';
// todo date
// todo string
// todo orderStatus
// todo list
// todo amount
// todo stringUpCase
export const ordersTableTitles = [
  {
    id: nanoid(3),
    name: 'Дата',
    dataTitle: 'createdAt',
    action: 'date',
    width: 100,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Змінено',
    dataTitle: 'updatedAt',
    action: 'date',
    width: 100,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Номер',
    dataTitle: 'orderNumber',
    action: 'string',
    width: 100,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Статус',
    dataTitle: 'orderStatus',
    action: 'orderStatus',
    width: 100,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Менеджер',
    dataTitle: 'manager',
    action: 'string',
    width: 120,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Вартість',
    dataTitle: 'amount',
    action: 'amount',
    width: 80,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Валюта',
    dataTitle: 'amount',
    action: 'string',
    width: 70,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Тип',
    dataTitle: 'orderType',
    action: 'orderType',
    width: 170,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Інвойси',
    dataTitle: 'invoices',
    action: 'list',
    width: 170,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Отримувач',
    dataTitle: 'reciever',
    action: 'string',
    width: 150,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Замовник',
    dataTitle: 'customer',
    action: 'string',
    width: 150,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'ТТН',
    dataTitle: 'ttnList',
    action: 'list',
    width: 170,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Перевізник',
    dataTitle: 'transporter',
    action: 'string',
    width: 120,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Призначення',
    dataTitle: 'destination',
    action: 'string',
    width: 100,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Склади',
    dataTitle: 'storeList',
    action: 'string',
    width: 150,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Склади',
    dataTitle: 'storeList',
    action: 'string',
    width: 150,
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Коментар',
    dataTitle: 'comment',
    action: 'comment',
    width: 200,
    filter: true,
    visible: true,
  },
];
