import { nanoid } from 'nanoid';
export const productsTableTitles = [
  {
    id: nanoid(3),
    name: 'Артикул (SKU)',
    dataTitle: 'sku',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Назва',
    dataTitle: 'name',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Автор',
    dataTitle: 'authorName',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'ID автора',
    dataTitle: 'authorId',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Ціна',
    dataTitle: 'price',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Валюта',
    dataTitle: 'currency',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Комісія, %',
    dataTitle: 'commision',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Секція',
    dataTitle: 'section',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Батьківська Категорія',
    dataTitle: 'parentCategory',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Категорія',
    dataTitle: 'category',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Наявність',
    dataTitle: 'stock',
    filter: true,
    visible: true,
  },
  {
    id: nanoid(3),
    name: 'Термін виг-ня, дні',
    dataTitle: 'manufacturingTime',
    filter: true,
    visible: false,
  },
  {
    id: nanoid(3),
    name: 'Пусто',
    dataTitle: 'empty',
    filter: false,
    visible: false,
  },
  {
    id: nanoid(3),
    name: 'Пусто',
    dataTitle: 'empty',
    filter: false,
    visible: false,
  },
  {
    id: nanoid(3),
    name: 'Пусто',
    dataTitle: 'empty',
    filter: false,
    visible: false,
  },
];
